services:
  turing-machine-ui:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    command: >
      /bin/bash -c "npm i && npm run dev -- --host"
    volumes:
      - './:/app'
    ports:
      - '3000:5173'
